packages:
  - software
  - workflow
  - model
  - ui
  - test
  - block

catalog:
  # SDK packages - EXACT VERSIONS (no ^ or ~)
  '@milaboratories/ts-builder': 1.2.12
  '@milaboratories/ts-configs': 1.2.1
  '@platforma-sdk/workflow-tengo': 5.9.0
  '@platforma-sdk/model': 1.58.5
  '@platforma-sdk/ui-vue': 1.58.8
  '@platforma-sdk/tengo-builder': 2.4.25
  '@platforma-sdk/package-builder': 3.11.4
  '@platforma-sdk/block-tools': 2.6.63
  '@platforma-sdk/eslint-config': 1.2.0
  '@platforma-sdk/test': 1.58.7
  '@milaboratories/helpers': 1.13.5
  '@milaboratories/strings': 0.1.1

  # Block-specific dependencies
  '@milaboratories/graph-maker': ^1.2.0
  '@milaboratories/multi-sequence-alignment': '^1.47.0'
  '@milaboratories/software-pframes-conv': ^2.2.9
  '@platforma-open/milaboratories.runenv-python-3': ^1.7.3
  '@platforma-open/soedinglab.software-mmseqs2': 1.18.0

  # Common dependencies - can use ^ or ~
  'vue': ^3.5.24
  'typescript': ~5.6.3
  'turbo': ^2.6.3
  'vitest': ^4.0.7
  'eslint': ^9.25.1
  '@changesets/cli': ^2.29.8
  'shx': ^0.4.0
