packages:
  - software
  - workflow
  - model
  - ui
  - test
  - block

catalog:
  '@platforma-sdk/model': ^1.46.0
  '@platforma-sdk/ui-vue': ^1.47.4
  '@platforma-sdk/workflow-tengo': ^5.6.6
  '@platforma-sdk/block-tools': ^2.6.26
  '@platforma-sdk/test': ^1.47.3
  '@platforma-sdk/tengo-builder': ^2.4.0
  '@platforma-sdk/package-builder': ^3.10.7
  '@platforma-sdk/eslint-config': ^1.1.0
  '@milaboratories/graph-maker': ^1.1.193
  '@milaboratories/multi-sequence-alignment': '^1.45.5'
  '@platforma-sdk/blocks-deps-updater': ^2.0.0

  '@milaboratories/software-pframes-conv': ^2.2.9
  '@platforma-open/milaboratories.runenv-python-3': ^1.7.3
  '@platforma-open/soedinglab.software-mmseqs2': 1.17.1

  'vue': ^3.5.25
  'vue-tsc': ^2.2.8

  'typescript': 5.5.4
  'tsup': ~8.3.5
  'turbo': ^2.5.4

  'vite': ^6.3.5
  'vitest': ^2.1.8
  '@vitejs/plugin-vue': ^5.2.4

  '@changesets/cli': ^2.29.4
