packages:
  - software
  - workflow
  - model
  - ui
  - test
  - block

catalog:
  "@platforma-sdk/model": ^1.32.1
  "@platforma-sdk/ui-vue": ^1.32.2
  "@platforma-sdk/workflow-tengo": ^4.7.0
  "@platforma-sdk/block-tools": ^2.5.51
  "@platforma-sdk/test": ^1.32.8
  "@platforma-sdk/tengo-builder": ^2.1.6
  "@platforma-sdk/package-builder": ^2.16.0
  "@platforma-sdk/eslint-config": ^1.0.3
  "@milaboratories/graph-maker": ^1.1.97

  "@milaboratories/software-pframes-conv": ^2.2.2
  "@platforma-open/milaboratories.runenv-python-3": 1.1.15
  "@platforma-open/soedinglab.software-mmseqs2": 1.17.0

  "vue": ^3.5.13
  "vue-tsc": ^2.2.8
  
  "typescript": ~5.5.4
  "tsup": ~8.3.5
  "turbo": ^2.5.4
  "js-yaml": ^4.1.0

  "vite": ^6.3.5
  "vitest": ^2.1.8
  "@vitejs/plugin-vue": ^5.2.4

  "@changesets/cli": ^2.29.4
