packages:
  - software
  - workflow
  - model
  - ui
  - test
  - block

catalog:
  "@platforma-sdk/model": ^1.30.3
  "@platforma-sdk/ui-vue": ^1.30.3
  "@platforma-sdk/workflow-tengo": ^4.1.4
  "@platforma-sdk/block-tools": ^2.5.43
  "@platforma-sdk/test": ^1.30.3
  "@platforma-sdk/tengo-builder": ^2.1.3
  "@platforma-sdk/package-builder": ^2.15.6
  "@platforma-sdk/eslint-config": ^1.0.3
  "@milaboratories/graph-maker": ^1.1.82

  '@milaboratories/software-pframes-conv': ^2.2.2
  "@platforma-open/milaboratories.runenv-python-3": ^1.1.12
  "@platforma-open/soedinglab.software-mmseqs2": ^1.0.0
  
  "vue": ^3.5.13
  "vue-tsc": ^2.2.8
  
  "typescript": ~5.5.4
  "tsup": ~8.3.5
  "turbo": ^2.4.4
  "js-yaml": ^4.1.0

  "vite": ^6.2.2
  "vitest": ^2.1.8
  "@vitejs/plugin-vue": ^5.2.1

  "@changesets/cli": ^2.28.1
